### ISSUE TITLE
pass-tomb sets the permssions of ~/.password-store to 711

### ISSUE THREAD

**Issue by ghost** [roddhjav/pass-tomb#23]
I tried changing the permissions back to 700 but after closing and opening the tomb again, the permissions are reset to 711. Is this intended?

**Comment by roddhjav** [comment]
Hi, this is because of [this line](https://github.com/roddhjav/pass-tomb/blob/master/tomb.bash#L192). In other words, pass-tomb re-initialise the permissions when opening the tomb. It might not be mandatory because the permissions are initialised anyway on tomb creation. I will test if I can get rid of this.
