### ISSUE TITLE
Write to tomb when closing tomb

### ISSUE THREAD

**Issue by lukasstevens** [roddhjav/pass-tomb#7]
Hello, I use ownCloud to store my password tomb so that I have it available on all my machines.
I noticed that every time I close the tomb it has to be uploaded again, even if I did not change anything. 
Since the tomb has changed the whole file has to be uploaded again which takes some 30 seconds on my internet connection. Is this intended behavior? Should I upload the tomb in another way?

**Comment by roddhjav** [comment]
This is because every-time you open the password tomb, the tomb file is modified (regardless your use of pass). Therefore the owncloud app re-upload the whole file. This is a normal behaviour.

From [tomb wiki](https://github.com/dyne/Tomb/wiki/Tombdropbox)
> Syncing changes to dropbox is very slow because dropbox sucks and doesn't handle deltas. If you are using similar programs, that handles deltas (sshfs, rsync, sparkleshare) this limitation is going to disappear.

You may want to use a different method like [sshfs](https://github.com/dyne/Tomb/wiki/Tombsshfs) or rsync.
